//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.WebServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertStudentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertAssessmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindTotalMarksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssessmentNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSingleColValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertOrUpdateMarksOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintGradeSheetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllAssessmentGradedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_WebServiceRef_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertStudentsCompletedEventHandler InsertStudentsCompleted;
        
        /// <remarks/>
        public event InsertAssessmentCompletedEventHandler InsertAssessmentCompleted;
        
        /// <remarks/>
        public event FindTotalMarksCompletedEventHandler FindTotalMarksCompleted;
        
        /// <remarks/>
        public event GetAssessmentNumberCompletedEventHandler GetAssessmentNumberCompleted;
        
        /// <remarks/>
        public event GetTableCompletedEventHandler GetTableCompleted;
        
        /// <remarks/>
        public event GetSingleColValueCompletedEventHandler GetSingleColValueCompleted;
        
        /// <remarks/>
        public event InsertOrUpdateMarksCompletedEventHandler InsertOrUpdateMarksCompleted;
        
        /// <remarks/>
        public event PrintGradeSheetCompletedEventHandler PrintGradeSheetCompleted;
        
        /// <remarks/>
        public event AllAssessmentGradedCompletedEventHandler AllAssessmentGradedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertStudents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool[] InsertStudents(Student[] list) {
            object[] results = this.Invoke("InsertStudents", new object[] {
                        list});
            return ((bool[])(results[0]));
        }
        
        /// <remarks/>
        public void InsertStudentsAsync(Student[] list) {
            this.InsertStudentsAsync(list, null);
        }
        
        /// <remarks/>
        public void InsertStudentsAsync(Student[] list, object userState) {
            if ((this.InsertStudentsOperationCompleted == null)) {
                this.InsertStudentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertStudentsOperationCompleted);
            }
            this.InvokeAsync("InsertStudents", new object[] {
                        list}, this.InsertStudentsOperationCompleted, userState);
        }
        
        private void OnInsertStudentsOperationCompleted(object arg) {
            if ((this.InsertStudentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertStudentsCompleted(this, new InsertStudentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertAssessment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertAssessment(Assessment a) {
            object[] results = this.Invoke("InsertAssessment", new object[] {
                        a});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertAssessmentAsync(Assessment a) {
            this.InsertAssessmentAsync(a, null);
        }
        
        /// <remarks/>
        public void InsertAssessmentAsync(Assessment a, object userState) {
            if ((this.InsertAssessmentOperationCompleted == null)) {
                this.InsertAssessmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertAssessmentOperationCompleted);
            }
            this.InvokeAsync("InsertAssessment", new object[] {
                        a}, this.InsertAssessmentOperationCompleted, userState);
        }
        
        private void OnInsertAssessmentOperationCompleted(object arg) {
            if ((this.InsertAssessmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertAssessmentCompleted(this, new InsertAssessmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindTotalMarks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FindTotalMarks() {
            object[] results = this.Invoke("FindTotalMarks", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FindTotalMarksAsync() {
            this.FindTotalMarksAsync(null);
        }
        
        /// <remarks/>
        public void FindTotalMarksAsync(object userState) {
            if ((this.FindTotalMarksOperationCompleted == null)) {
                this.FindTotalMarksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindTotalMarksOperationCompleted);
            }
            this.InvokeAsync("FindTotalMarks", new object[0], this.FindTotalMarksOperationCompleted, userState);
        }
        
        private void OnFindTotalMarksOperationCompleted(object arg) {
            if ((this.FindTotalMarksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindTotalMarksCompleted(this, new FindTotalMarksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAssessmentNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetAssessmentNumber(string type) {
            object[] results = this.Invoke("GetAssessmentNumber", new object[] {
                        type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssessmentNumberAsync(string type) {
            this.GetAssessmentNumberAsync(type, null);
        }
        
        /// <remarks/>
        public void GetAssessmentNumberAsync(string type, object userState) {
            if ((this.GetAssessmentNumberOperationCompleted == null)) {
                this.GetAssessmentNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssessmentNumberOperationCompleted);
            }
            this.InvokeAsync("GetAssessmentNumber", new object[] {
                        type}, this.GetAssessmentNumberOperationCompleted, userState);
        }
        
        private void OnGetAssessmentNumberOperationCompleted(object arg) {
            if ((this.GetAssessmentNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssessmentNumberCompleted(this, new GetAssessmentNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTable(string table, string col) {
            object[] results = this.Invoke("GetTable", new object[] {
                        table,
                        col});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTableAsync(string table, string col) {
            this.GetTableAsync(table, col, null);
        }
        
        /// <remarks/>
        public void GetTableAsync(string table, string col, object userState) {
            if ((this.GetTableOperationCompleted == null)) {
                this.GetTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableOperationCompleted);
            }
            this.InvokeAsync("GetTable", new object[] {
                        table,
                        col}, this.GetTableOperationCompleted, userState);
        }
        
        private void OnGetTableOperationCompleted(object arg) {
            if ((this.GetTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableCompleted(this, new GetTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSingleColValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetSingleColValue(string get, string type) {
            object[] results = this.Invoke("GetSingleColValue", new object[] {
                        get,
                        type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetSingleColValueAsync(string get, string type) {
            this.GetSingleColValueAsync(get, type, null);
        }
        
        /// <remarks/>
        public void GetSingleColValueAsync(string get, string type, object userState) {
            if ((this.GetSingleColValueOperationCompleted == null)) {
                this.GetSingleColValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSingleColValueOperationCompleted);
            }
            this.InvokeAsync("GetSingleColValue", new object[] {
                        get,
                        type}, this.GetSingleColValueOperationCompleted, userState);
        }
        
        private void OnGetSingleColValueOperationCompleted(object arg) {
            if ((this.GetSingleColValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSingleColValueCompleted(this, new GetSingleColValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertOrUpdateMarks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertOrUpdateMarks(int std_id, int a_id, int marks, bool update) {
            object[] results = this.Invoke("InsertOrUpdateMarks", new object[] {
                        std_id,
                        a_id,
                        marks,
                        update});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertOrUpdateMarksAsync(int std_id, int a_id, int marks, bool update) {
            this.InsertOrUpdateMarksAsync(std_id, a_id, marks, update, null);
        }
        
        /// <remarks/>
        public void InsertOrUpdateMarksAsync(int std_id, int a_id, int marks, bool update, object userState) {
            if ((this.InsertOrUpdateMarksOperationCompleted == null)) {
                this.InsertOrUpdateMarksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertOrUpdateMarksOperationCompleted);
            }
            this.InvokeAsync("InsertOrUpdateMarks", new object[] {
                        std_id,
                        a_id,
                        marks,
                        update}, this.InsertOrUpdateMarksOperationCompleted, userState);
        }
        
        private void OnInsertOrUpdateMarksOperationCompleted(object arg) {
            if ((this.InsertOrUpdateMarksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertOrUpdateMarksCompleted(this, new InsertOrUpdateMarksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintGradeSheet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PrintGradeSheet() {
            object[] results = this.Invoke("PrintGradeSheet", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PrintGradeSheetAsync() {
            this.PrintGradeSheetAsync(null);
        }
        
        /// <remarks/>
        public void PrintGradeSheetAsync(object userState) {
            if ((this.PrintGradeSheetOperationCompleted == null)) {
                this.PrintGradeSheetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintGradeSheetOperationCompleted);
            }
            this.InvokeAsync("PrintGradeSheet", new object[0], this.PrintGradeSheetOperationCompleted, userState);
        }
        
        private void OnPrintGradeSheetOperationCompleted(object arg) {
            if ((this.PrintGradeSheetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintGradeSheetCompleted(this, new PrintGradeSheetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllAssessmentGraded", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AllAssessmentGraded() {
            object[] results = this.Invoke("AllAssessmentGraded", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AllAssessmentGradedAsync() {
            this.AllAssessmentGradedAsync(null);
        }
        
        /// <remarks/>
        public void AllAssessmentGradedAsync(object userState) {
            if ((this.AllAssessmentGradedOperationCompleted == null)) {
                this.AllAssessmentGradedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllAssessmentGradedOperationCompleted);
            }
            this.InvokeAsync("AllAssessmentGraded", new object[0], this.AllAssessmentGradedOperationCompleted, userState);
        }
        
        private void OnAllAssessmentGradedOperationCompleted(object arg) {
            if ((this.AllAssessmentGradedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllAssessmentGradedCompleted(this, new AllAssessmentGradedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Student {
        
        private string fnameField;
        
        private string lnameField;
        
        /// <remarks/>
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
            }
        }
        
        /// <remarks/>
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Assessment {
        
        private System.DateTime dateField;
        
        private string typeField;
        
        private int marksField;
        
        /// <remarks/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int marks {
            get {
                return this.marksField;
            }
            set {
                this.marksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertStudentsCompletedEventHandler(object sender, InsertStudentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertAssessmentCompletedEventHandler(object sender, InsertAssessmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertAssessmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertAssessmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void FindTotalMarksCompletedEventHandler(object sender, FindTotalMarksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindTotalMarksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindTotalMarksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAssessmentNumberCompletedEventHandler(object sender, GetAssessmentNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssessmentNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssessmentNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetTableCompletedEventHandler(object sender, GetTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetSingleColValueCompletedEventHandler(object sender, GetSingleColValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSingleColValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSingleColValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertOrUpdateMarksCompletedEventHandler(object sender, InsertOrUpdateMarksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertOrUpdateMarksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertOrUpdateMarksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PrintGradeSheetCompletedEventHandler(object sender, PrintGradeSheetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintGradeSheetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintGradeSheetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AllAssessmentGradedCompletedEventHandler(object sender, AllAssessmentGradedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllAssessmentGradedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllAssessmentGradedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591